version: "3.8"

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"
    networks:
      - backend-rinha
      - payment-processor

  backend1:
    build: .
    container_name: backend1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_MASTER=true
      - PAYMENT_WORKERS_COUNT=2
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "140MB"
    depends_on:
      - redis
    networks:
      - backend-rinha
      - payment-processor

  backend2:
    build: .
    container_name: backend2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_MASTER=false
      - PAYMENT_WORKERS_COUNT=2
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "140MB"
    depends_on:
      - redis
    networks:
      - backend-rinha
      - payment-processor

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - backend1
      - backend2
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"
    networks:
      - backend-rinha

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
  payment-processor:
    external: true
